### ISSUE TITLE
Doubt about use.

### ISSUE THREAD

**Issue by maximilianoalves** [RC-Platform-Disco-Team/gatling-mongodb-protocol#5]
Hello, I searched in your readme how I can use your project, but i am not finding. How I can use your project? Only copy your code or I can add in my project with dependency, plugin or something like this?

Thanks for helping me.

**Comment by krasilnikov-dmitriy** [comment]
If you use sbt you could import it via GitHub link:

`lazy val mongoGatlingProtocolProject = RootProject(uri("git://github.com/RC-Platform-Disco-Team/gatling-mongodb-protocol.git"))`

also see https://stackoverflow.com/questions/7550376/how-can-sbt-pull-dependency-artifacts-from-git
